/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClientController;
import javax.swing.JOptionPane;
import model.User;

/**
 *
 * @author khanh
 */
public class GameForm extends javax.swing.JFrame {
    private User user;
    private ClientController controller;
    
    /**
     * Creates new form GameForm
     */
    public GameForm(User user, ClientController controller) {
        initComponents();
        this.user = user;
        this.controller = controller;
        
        Runnable listenServer = new Runnable() {
            @Override
            public void run() {
                while(!Thread.currentThread().isInterrupted()){
                    Object o = controller.recieveData();
                    if(o instanceof Boolean){
                        Boolean isWinner = (Boolean) o;
                        if(isWinner) 
                            JOptionPane.showMessageDialog(rootPane, "You are the winner");
                        else JOptionPane.showMessageDialog(rootPane, "You are the fucking loser");
                    }
                }
            }
        };
        
        Thread t = new Thread(listenServer);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnWin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnWin.setText("Win");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(btnWin)
                .addContainerGap(187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnWin)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnWin;
    // End of variables declaration//GEN-END:variables
}
