/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClientController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Message;
import model.User;

/**
 *
 * @author khanh
 */
public class ListPlayerForm extends javax.swing.JFrame {
    private User user;
    private ClientController controller;
    DefaultTableModel model;
    Boolean shutdown = false;

    /**
     * Creates new form List
     */
    public ListPlayerForm(User user, ClientController controller) {
        initComponents();
        this.user = user;
        this.controller = controller;
        this.setTitle(user.getUsername() + " client");
        model =(DefaultTableModel)tblPlayer.getModel();
        Message request = new Message(true, Message.MessageType.GETFRIEND);
        controller.sendData(request);
        
        Runnable listenChallenge = new Runnable() {
            @Override
            public void run() {
                while(!shutdown){
                    Object o = controller.recieveData();
                    if(o instanceof String){
                        System.out.println("Some one challege");
                        String opponent = (String)o;
                        Message response = new Message();
                        response.setType(Message.MessageType.CHALLENGE);
                        Boolean accept = (JOptionPane.showConfirmDialog(null, 
                                opponent + " want to challege you in a chess game") 
                                == JOptionPane.YES_OPTION);
                        response.setObject(accept);
                        controller.sendData(response);
                        if(accept){
                            close();
                            new GameForm(user, controller).setVisible(true);
                            
                            System.out.println("interupt list form");
                        }
                    }else if(o instanceof Boolean){
                        System.out.println("Challege response");
                        Boolean accept = (Boolean) o;
                        if(accept){
                            close();
                            new GameForm(user, controller).setVisible(true);
                        }
                    } else if(o instanceof ArrayList){
                        System.out.println("GET FRIEND");
                        ArrayList<String> players = (ArrayList<String>) o;
                        model.setRowCount(0);
                        for(String s: players){
                            Object[] ob = {s};
                            model.addRow(ob);
                        }
                    }
                } 
            }
        };
        Thread t = new Thread(listenChallenge);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReload = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPlayer = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnReload.setText("Reload");
        btnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadActionPerformed(evt);
            }
        });

        tblPlayer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPlayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPlayerMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPlayer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnReload))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnReload))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadActionPerformed
        // TODO add your handling code here:
        Message request = new Message(true, Message.MessageType.GETFRIEND);
        controller.sendData(request);
    }//GEN-LAST:event_btnReloadActionPerformed

    private void tblPlayerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPlayerMouseClicked
        // TODO add your handling code here:
        int row = tblPlayer.getSelectedRow();
        String opponent = model.getValueAt(row, 0).toString();
        Message request = new Message(opponent, Message.MessageType.CHALLENGE);
        controller.sendData(request);
    }//GEN-LAST:event_tblPlayerMouseClicked

    void close(){
        dispose();
        shutdown = true;
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReload;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPlayer;
    // End of variables declaration//GEN-END:variables
}
